language: node_js

matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    node_js: 8
    addons:
      apt:
        packages:
           - libxrandr-dev
           - libxinerama-dev
           - libxcursor-dev
           - libxi-dev
  - os: osx # OSX 10.12
    node_js: 8


install:
- travis_retry npm install -g esy@0.2.11
- travis_wait esy install
script:
- travis_wait esy build
cache:
  timeout: 360
  directories:
  - "$HOME/.esy/"
