language: node_js
os:
- osx
- linux
node_js:
- '8'
install:
- travis_retry npm install -g esy@0.2.11
- travis_wait esy install
script:
- travis_wait esy build
cache:
  timeout: 360
  directories:
  - "$HOME/.esy/"
